//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeJam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Character
    {
        public int CharID { get; set; }
        public string Id { get; set; }
        public string CharName { get; set; }
        public int Height { get; set; }
        public int Weight { get; set; }

        [Range(0, 75, ErrorMessage = "ThreePoint must be between 0 and 75")]
        public int ThreePoint { get; set; }
        [Range(0, 75, ErrorMessage = "FieldGoal must be between 0 and 75")]
        public int FieldGoal { get; set; }
        [Range(0, 75, ErrorMessage = "Paint must be between 0 and 75")]
        public int Paint { get; set; }
        [Range(0, 75, ErrorMessage = "Steal must be between 0 and 75")]
        public int Steal { get; set; }
        [Range(0, 75, ErrorMessage = "Block must be between 0 and 75")]
        public int Block { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
