//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeJam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int CharID { get; set; }
        public int UserID { get; set; }
        public string CharName { get; set; }
        public int Height { get; set; }
        public int Weight { get; set; }
        public int ThreePoint { get; set; }
        public int FieldGoal { get; set; }
        public int Paint { get; set; }
        public int Steal { get; set; }
        public int Block { get; set; }
    
        public virtual User User { get; set; }
    }
}
