//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeJam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PokeTier
    {
        public int PokeID { get; set; }
        public int Tiers { get; set; }
        public string PokeName { get; set; }
    }
}
